[context.production]
  command = "yarn build"
  publish = "dist"

[[redirects]]
  from = "https://mikesprague-me.netlify.com/*"
  to = "https://mikesprague.me/:splat"
  status = 301

[[redirects]]
  from = "https://mikesprague-me.netlify.com/*"
  to = "https://m12e.me/:splat"
  status = 301

[[redirects]]
  from = "https://mikesprague-me.netlify.com/*"
  to = "https://m5l.me/:splat"
  status = 301